### ISSUE TITLE
【問題】speedtest.exe 壞掉了！

### ISSUE THREAD

**Issue by YuiTatsumi** [orz811017/boost_bandwidth_via_speedtest#2]
我原本都將 speedtest.exe 放在 Windows 的開機啟動資料夾內，今天開機就跳出壞掉的提示框！謝謝😂。

**Comment by mw33h** [comment]
Error message:
speedtest-cli
Retrieving speedtest.net configuration...
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/speedtest", line 33, in <module>
    sys.exit(load_entry_point('speedtest-cli==2.1.2', 'console_scripts', 'speedtest')())
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/speedtest_cli-2.1.2-py3.9.egg/speedtest.py", line 1880, in main
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/speedtest_cli-2.1.2-py3.9.egg/speedtest.py", line 1836, in shell
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/speedtest_cli-2.1.2-py3.9.egg/speedtest.py", line 1093, in __init__
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/speedtest_cli-2.1.2-py3.9.egg/speedtest.py", line 1175, in get_config
ValueError: invalid literal for int() with base 10: ''

**Comment by vincent-chang-rightfighter** [comment]
https://github.com/sivel/speedtest-cli/commit/cadc68b5aef20f28648072cf07a8f155639b81dd

change speedtest.py

it works again

```
1175       ignore_servers = [
1176            int(i) for i in server_config['ignoreids'].split(',') if i
1177        ]
```

**Comment by orz811017** [comment]
I'll change it later, thanks all of you.

**Comment by orz811017** [comment]
done. please pull the latest patch.
